# Введение в статистику {#intro}

## Исходные понятия статистики

**Статистика** --- это междисциплинарная область знаний, а также практической деятельности, изучающая массовые явления, а также прицнипи и методы работы с данными, характеризующими эти явления.

Звучит красиво. Осталось понять, что это значит.

Массовые явления затрагивают огромные массы людей. Огромность масс, конечно, различна. Скажем, базовые перцептивные закономерности, связанные с тем, как устроена зрительная система, охватывают *всех людей*. Уровень удовлетворенности жизнью россиян охватывает только *население России*. Городские блага москвичей --- только для *жителей Москвы*. Учебная мотивация студентов департамента психологии НИУ ВШЭ --- это только про *людей с психологических бакалариата и магистратур НИУ ВШЭ*.

**Генеральная совокупность** --- множество всех [существующих] исследуемых объектов, а также сведения о них.

**Объем совокупности** ($N$) --- число единиц, образующих совокупность.

Короче, надо исследовать много людей, а времени и денег нет. Приходится из генеральной совокупности извлекать **выборку** --- некоторую часть нашей генеральной совокупности (объемом $n$).

Нас, конечно же, интересуют какие-то **признаки**, которыми обладают объект нашей генеральной совокупности. Эти признаки могут быть выражены *количественно* в определенных **показателях**.

Например,

| Признак                    | Показатель                                             |
|----------------------------|--------------------------------------------------------|
| Рабочая память             | Объем рабочей памяти                                   |
| Нейротизм                  | Уровень нейротизма по BFI                              |
| Заработная плата           | Средняя заработная плата                               |
| Когнитивная нагрузка       | Уровень когнитивной нагрузки по ЭЭГ-коррелятам         |
| Доверие к ИИ               | Уровень доверия к ИИ по опроснику TAIA                 |
| Индивидуализм/коллективизм | Индекс индивидуализма/коллективизма по модели Хофстеде |

Признаки могут быть очень разными, как и показатели, которыми мы их пытаемся измерить. Не будем сильно в это углубляться, ибо этим занимается теория измерений, а мы тут статистикой пришли заниматься.

Что нам важно сейчас: генеральная совокупность характеризуется параметром.

**Параметр** --- относительно постоянная [от одной совокупности к другой] величина, характеризующая генеральную совокупность по некоторому показателю.

Ну, то есть в принципе существует *средний уровень нейротизма по BFI студента-психолога* или *индекс индивидуализма/коллетивизма для конкретной культуры*. Проблема в том, что величина параметра, который мы изучаем, неизвестна. И никогда не будет известна.

Но почему?

* Мы не можем изучать всю генеральную совокупность --- слишком много объектов
* Наши измерения всегда содержат ошибку --- мы даже длину линейкой точно не можем измерить, что уж о психологических измерениях говорить

Поэтому величину параметра мы можем только предсказать с определённой статистической точностью. Измеряя что-либо на выборке, мы получаем **выборочная характеристика (оценку)** --- эмпирический (измеримый) аналог параметра.


## Зачем нужна статистика?


## Выборка должна быть репрезентативна


